### ISSUE TITLE
Update README.md for MacOS (Apple Silicon) Project Setup Instructions.

### ISSUE THREAD

**Issue by jsontm** [ASU-CodeDevils/devil_bot_rust#1]
Update the "Set up project for AL2 target MacOS (Apple Silicon)" `README.md` instructions so that the linker works for cross-compilation into`x86_64-unknown-linux-musl`. I believe the current linker from `sudo apt install gcc-x86-64-linux-gnu` should work fine, but we need to set up a proper symlink so that it works out of the box for devs without any extra configuration. They should be able to follow the `README.md` to a T and have the project build and deploy successfully.

**Comment by stucamp** [comment]
Does "sudo apt" work on a mac?  

Once the correct x86_64 linker install command and reference is in the build-function.sh... the setup instructions in README.md should suffice.  

As a side note, while cross-compiling for aarch64, needed to export reference to x86_64 linker in env, given that some crates will also need to have access to the cross-compile linker.  See `export CC_x86_64_unknown_linux_musl=x86_64-linux-gnu-gcc` on line 13 of build-function.sh.  Have a suspicion that the arm64 M1 cross-compile will need to do something similar
