### ISSUE TITLE
Create a DevilBot "Slack App" to Set-up OAuth

### ISSUE THREAD

**Issue by jsontm** [ASU-CodeDevils/devil_bot_rust#4]
In our Slack workspace, we should make a new Slack App similar to "Flameboi", maybe just copy the permissions over from that previous app. Then communicate in the `#devilbot-dev` Slack channel the new OAuth creds so we can configure API Gateway accordingly.

**Comment by reharri7** [comment]
IP

**Comment by reharri7** [comment]
Done
