### ISSUE TITLE
Make a post ephemeral message

### ISSUE THREAD

**Issue by reharri7** [ASU-CodeDevils/devil_bot_rust#42]
[Use this documentation](https://api.slack.com/methods/chat.postEphemeral/test) to make a method for ephemeral messages. This will be a reusable feature to post messages in channels that are only visible to the user that is passed in.

**Comment by jsontm** [comment]
We can use slack-morphism for this, method is here: https://github.com/abdolence/slack-morphism-rust/blob/master/src/api/chat.rs#L75

The request structure is as follows:
```rust
pub struct SlackApiChatPostEphemeralRequest {
    pub channel: SlackChannelId,
    pub user: SlackUserId,
    pub content: SlackMessageContent,
    pub as_user: Option<bool>,
    pub icon_emoji: Option<String>,
    pub icon_url: Option<String>,
    pub link_names: Option<bool>,
    pub parse: Option<String>,
    pub thread_ts: Option<SlackTs>,
    pub username: Option<String>,
}
```
