### ISSUE TITLE
Create Unified POSIX setup (Mac and Linux)

### ISSUE THREAD

**Issue by stucamp** [ASU-CodeDevils/devil_bot_rust#9]
- [x] Amend README.md to reflect creation of a unified POSIX (Mac and LInux) setup instruction
- [x] Amend build-function.sh to automatically configure, build, and install requisite packages for rust and npm based on kernel/architecture.

**Comment by reharri7** [comment]
For Apple silicon too?👀

**Comment by stucamp** [comment]
> For Apple silicon too?eyes

Lol, just using what you guys had done previously on Apple Silicon, but if that worked, this should.
